import json
import os
from datetime import datetime
import uuid
import logging

logger = logging.getLogger(__name__)

class ComplaintService:
    """Service to handle JSON-based civic complaints persistence."""
    _complaints_db = []
    _db_path = os.path.join(os.path.dirname(__file__), "..", "..", "complaints.json")

    @classmethod
    def load_complaints(cls):
        """Load complaints from local JSON file. Create if missing."""
        if not os.path.exists(cls._db_path):
            cls._save_to_disk()
            logger.info("Created new complaints.json database.")
        else:
            try:
                with open(cls._db_path, "r", encoding="utf-8") as f:
                    cls._complaints_db = json.load(f)
                logger.info(f"Loaded {len(cls._complaints_db)} complaints from disk.")
            except Exception as e:
                logger.error(f"Failed to load complaints.json: {e}")
                cls._complaints_db = []

    @classmethod
    def _save_to_disk(cls):
        """Persist the in-memory database to disk."""
        try:
            with open(cls._db_path, "w", encoding="utf-8") as f:
                json.dump(cls._complaints_db, f, indent=4)
        except Exception as e:
            logger.error(f"Failed to write to complaints.json: {e}")

    @classmethod
    def save_complaint(cls, complaint_data: dict) -> dict:
        """Create and store a new complaint with an autogenerated ID and timestamp."""
        complaint = {
            "id": str(uuid.uuid4()),
            "status": "Filed",
            "timestamp": datetime.utcnow().isoformat() + "Z",
            **complaint_data
        }
        cls._complaints_db.append(complaint)
        cls._save_to_disk()
        return complaint

    @classmethod
    def get_all_complaints(cls) -> list[dict]:
        """Retrieve all complaints sorted by newest first."""
        return sorted(cls._complaints_db, key=lambda x: x["timestamp"], reverse=True)

    @classmethod
    def update_complaint_status(cls, complaint_id: str, new_status: str) -> dict:
        """Update the status of an existing complaint by ID."""
        for complaint in cls._complaints_db:
            if complaint["id"] == complaint_id:
                complaint["status"] = new_status
                cls._save_to_disk()
                return complaint
        return None
